### ISSUE TITLE
Introduce pragma to disable UTF-8 in the lexer

### ISSUE THREAD

**Issue by Hywan** [hoaproject/Compiler#52]
In some grammars, we need the lexer to not be in Unicode mode. For instance, in `Hoa\Json`. So we need to introduce pragma, and the first one would aim to disable Unicode. Something like:
```
%pragma unicode false
```
In some days, we will need to implement the following one too:
```
%pragma backtrack_limit 3
```
(for an LL(3) compiler)

Maybe the names are not correct. I need your help here!

**Comment by Jir4** [comment]
For the `unicode` pragma i'd prefer something like `enable_unicode`

**Comment by Hywan** [comment]
Thoughts @hoaproject/hoackers?

**Comment by CircleCode** [comment]
@Jir4 I'd name it according to its default: the purpose is not to enable UTF8, but rather to disable it, so the pragma would be `disable_unicode true`

@Hywan if we introduce such pragma (whatever it is named), compiler need a command to list all the pragma it support (with their explanation) so that grammar authors can use them.

At least, pragma would be used by the lexer or the compiler. Isn't it useful di differentiate them? if yes, I see 2 ways:
-   2 pragma définitions, isolated, with for example `%compiler.pragma…` and `%lexer.pragma…`
-   pragma differentiated by their name (thus not isolated at all, but semantically recognisable)

@Hywan Another to think about is what other usages of pragma do we think about?

For example, I thought about it when working on a markdown parser, and I needed some kind of _var_ for _tab-length_. Would your pragma idea solve this? would the pragama values be usable inside the grammar, or only used by the compiler itself (or am I out of topic?)
In the case pragma could be used by the compiler, maybe a 3rd pragma definition would be `%grammar.pragma…`

I know I leave more questions than answers, sorry ;-)

**Comment by Hywan** [comment]
@CircleCode I don't lie `disable_unicode` but I don't know why so far…

Yes, having “namespaced” pragma is not a bad idea. We must look what other grammar description languages do.

About your markdown proposal, you're talking about variables. A pragma is a directive that “configure” the compiler behavior. This is not variable. Moreover, if a language need variable, this is just a so bad practise I can't imagine it. A language must be determinist :-/.

**Comment by Jir4** [comment]
@CircleCode i don't really like double negation names :s

**Comment by CircleCode** [comment]
> Moreover, if a language need variable, this is just a so bad practise I can't imagine it. A language must be determinist :-/.

This is another debate we don't want to have here ;-)

> A pragma is a directive that “configure” the compiler behavior. This is not variable.

Ok, got it

> I don't like disable_unicode but I don't know why so far…

Maybe because of the _disable_ part. What about `no_unicode_parsing` (or simpler if namespaced)?

**Comment by Jir4** [comment]
> Maybe because of the disable part. What about no_unicode_parsing (or simpler if namespaced)?

Mainly because a `enable = true` is way simpler in a mind than a `disable = false`
In all case, i think we need something to list all pragma.

**Comment by Hywan** [comment]
@CircleCode @Jir4 Define “something” to list all pragmas, please? A command-line tool? An exhaustive list in the documentation?

So, what about:
```
%pragma lexer.unicode true|false
```
?

**Comment by CircleCode** [comment]
`%pragma lexer.unicode true|false` is fine for me, clear, simple, minimalistic, efficient

_something_ to list pragmas would be an option or a command of the compiler cli.
Maybe this is just the right time to begin some kind of man pages for the bin commands? I know we can't do true man pages because of windows support, but some kind of extended help right from the command itself?

**Comment by Hywan** [comment]
@CircleCode We can still introduce a `hoa help` command that will fallback to `man` if exists, else emulate?

**Comment by Hywan** [comment]
@CircleCode Please, open an issue in `hoa/cli`.

**Comment by Jir4** [comment]
:+1: for `lexer.unicode`

**Comment by jubianchi** [comment]
:+1: for `%pragma lexer.unicode true|false`

**Comment by Hywan** [comment]
Used in https://github.com/hoaproject/Json/pull/18.

**Comment by Hywan** [comment]
See https://github.com/hoaproject/Compiler/pull/53.

Thanks for all your answers!

**Comment by Hywan** [comment]
(especially see https://github.com/Hywan/Compiler/commit/addf18dbd5b9102e157ceb7bae334208ea64d4dc)
